### PR TITLE
Adds scala 2.13 to travis CI

### PR DESCRIPTION
**Pull request by calvinbrown085**
@amohrland https://github.com/Banno/kafka4s/issues/8

@francescopellegrini

### CODE REVIEW

**Comment by francescopellegrini** [comment]
It looks like you are depending on some libraries not yet available for Scala 2.13:

- Kafka started supporting Scala 2.13 from v2.4.0
- discipline added Scala 2.13 support [last June](https://github.com/typelevel/discipline/commit/49e7c80ba90c6ada8cfc2dc76f18933013a1fdcd#diff-fdc3abdfd754eeb24090dbd90aeec2ce).
- scalacheck-magnolia doesn't support Scala 2.13 yet

**Comment by calvinbrown085** [comment]
@francescopellegrini Yep.. I see that. Well looks like we may need to hold off on this one!

**Comment by amohrland** [comment]
@francescopellegrini Good catch(es), thanks. Going to reopen https://github.com/Banno/kafka4s/issues/8 till scalacheck-magnolia supports 2.13 (or we replace or remove it).

**Comment by AdrianRaFo** [comment]
This one seems more updated and has cross-compilation to scala 2.13 https://github.com/ChocPanda/scalacheck-magnolia

**Comment by coacoas** [comment]
@calvinbrown085 Are you looking to get this updated with the latest versions specified?

**Comment by calvinbrown085** [comment]
@coacoas I haven't in a bit, but I can today

**Comment by coacoas** [comment]
@calvinbrown085 Is there anything I can do to get this moving? Or will you have a chance to get this done today? I know you're really busy right now.

**Comment by calvinbrown085** [comment]
@coacoas I haven't looked at it harder, I think I just need to double check if this is possible to move to 2.13 yet or not. If you have time to grab this that would be 👍 it would unblock our kafka projects to move to 2.13

**Comment by calvinbrown085** [comment]
I'm going to close this, as I won't get back to it ATM.

**Pull request closed without merging**
