### PR TITLE
Removing stream constructor from ProducerApi and ConsumerApi

### PR DESCRIPTION
**Pull request by calvinbrown085**
addresses https://github.com/Banno/kafka4s/issues/47

Please let me know if I missed something :)

### CODE REVIEW

**Comment by zcox** [comment]
@calvinbrown085 I think the changes look good, can you try running `scalafmtAll`? That may fix the build.

**Comment by calvinbrown085** [comment]
@zcox It will, I just ran `scalafmt`, i'll run that here.

**Comment by calvinbrown085** [comment]
🤞 Lets see if this does the trick.

**Comment by zcox** [comment]
Sorry, one more thing: we have example code duplicated in both `README.md` (for users landing on https://github.com/Banno/kafka4s) and `docs/src/main/tut/index.md` (for users landing on https://banno.github.io/kafka4s). Could you also update that example in `index.md`?

Also for that example code, I was copying from example3, I'm not sure the new example code in `README.md` will continually write integers to the topic, will it just write one and then close?

**Comment by calvinbrown085** [comment]
@zcox I had copied from example3, let take another look to make sure I didn't miss something

**Comment by calvinbrown085** [comment]
Hm, so the build passes.. @zcox I'm not sure on this one. It seems to be the same semantics does it not?

**Comment by calvinbrown085** [comment]
Yeah no problem!

**Pull request merged**
