### PR TITLE
fix: build.sbt  Scala Version upgrade to 2.13.7 deprecated toIterable…

### PR DESCRIPTION
**Pull request by ERobertGII**
…; changed to toSeq

### CODE REVIEW

**Review by zcox — APPROVED** [review]
Should we also change to 2.13.7 in these files? https://github.com/Banno/kafka4s/tree/master/.github/workflows I'm not super familiar with github workflows yet. Looking at the checks below and wondering how to get it to use 2.13.7.

**Review by Kazark — APPROVED** [review]
👏 Welcome to `kafka4s` 👏

**Comment by Kazark** [comment]
> Should we also change to 2.13.7 in these files? https://github.com/Banno/kafka4s/tree/master/.github/workflows I'm not super familiar with github workflows yet.

Good catch @zcox , I imagine we should. Though @amohrland understands those best.

**Comment by amohrland** [comment]
>change to 2.13.7 in these files
 
Yep, good idea - should be safe to update those

**Review by amohrland — APPROVED** [review]
👍

**Pull request merged**
